// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwndnbgqduqpycmpusaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3bmRuYmdxZHVxcHljbXB1c2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExOTg3NTUsImV4cCI6MjA4Njc3NDc1NX0.eQCkY4IROiALjnPGd47JmeNwtccn5qdN6B-p-8c4JWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});